apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: zoo-0
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        petindex: "0"
    spec:
      containers:
        - name: zookeeper
          image: zookeeper
          env:
            - name: ZOO_MY_ID
              value: "1"
            - name: ZOO_SERVERS
              value: server.1=zoo-0.kafka.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: leader-election
          readinessProbe:
            exec:
              command:
                - zkCli.sh
                - ls
                - /
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir
              mountPath: /tmp/zookeeper
            - name: opt
              mountPath: /opt/
      volumes:
        - name: opt
          emptyDir: {}
        - name: datadir
          emptyDir: {}
