apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: zoo-2
  namespace: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
        petindex: "2"
    spec:
      containers:
        - name: zookeeper
          image: zookeeper
          env:
            - name: ZOO_MY_ID
              value: "2"
            - name: ZOO_SERVERS
              value: server.0=zoo-0:2888:3888 server.1=zoo-1:2888:3888 server.2=zoo-2:2888:3888
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: peer
            - containerPort: 3888
              name: leader-election
          readinessProbe:
            exec:
              command:
                - zkCli.sh
                - ls
                - /
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir
              mountPath: /tmp/zookeeper
            - name: opt
              mountPath: /opt/
      volumes:
        - name: opt
          emptyDir: {}
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir-zoo-2
